---
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
roles:
  - name: nginx
    src: https://github.com/punktDe/ansible-proserver-nginx
  - name: dehydrated
    src: https://github.com/punktDe/ansible-proserver-dehydrated
  - name: system
    src: https://github.com/punktDe/ansible-proserver-system
  - name: maildev
    src: https://github.com/punktDe/ansible-maildev
  - name: oauth2_proxy
    src: https://github.com/punktDe/ansible-proserver-oauth2-proxy
  - name: supervisord
    src: https://github.com/punktDe/ansible-proserver-supervisord
