---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Mailpit service is running
      ansible.builtin.service:
        name: mailpit
        state: started
      check_mode: yes
      register: service_status

    - name: Verify service is enabled
      ansible.builtin.assert:
        that:
          - "not service_status.changed"

    - name: Check Mailpit UI port (8025)
      ansible.builtin.wait_for:
        port: 8025
        host: 127.0.0.1
        timeout: 60

    - name: Check Mailpit SMTP port (1025)
      ansible.builtin.wait_for:
        port: 1025
        host: 127.0.0.1
        timeout: 60
