---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Mailpit service is running
      ansible.builtin.command: systemctl status mailpit
      register: service_status
      changed_when: false
      failed_when: false

    - name: Verify service is active
      ansible.builtin.assert:
        that: "'active (running)' in service_status.stdout"

    - name: Check Mailpit UI port (8025)
      ansible.builtin.wait_for:
        port: 8025
        host: 127.0.0.1
        timeout: 60

    - name: Check Mailpit SMTP port (1025)
      ansible.builtin.wait_for:
        port: 1025
        host: 127.0.0.1
        timeout: 60
